FROM python:3.11-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY alembic.ini ./mirgration/
COPY ./alembic ./mirgration/alembic

COPY ./app/core ./mirgration/app/core
COPY ./app/db ./mirgration/app/db
COPY ./app/models ./mirgration/app/models

WORKDIR ./mirgration

CMD ["alembic", "upgrade", "head"]
